### ISSUE TITLE
Histories & Ymboxes render in the reverse order

### ISSUE THREAD

**Issue by rezbyte** [rezbyte/yaml_cv_rs#1]
Histories & ymboxes render in the opposite order they're specified in `data.yaml`.
I.e.
```yaml
licences:
  - 
    year: 19XX
    month: 11
    value: 普通自動車免許
  - 
    year: 20XX
    month: 11
    value: 履歴書検定1級

```
Renders as:
20XX 11 履歴書検定1級
19XX 11 普通自動車免許
